<?php

namespace Avocadesign\StatamicTools\Site;

use Illuminate\Support\Str;
use Statamic\Fields\Field;
use Statamic\Fields\Fields;

/**
 * The AI block catalogue: every page builder block and text editor set with its guidance and fields, as
 * markdown. The addon only builds it. Each site commits the file at site.catalogue_path beside its guidance
 * files, and avoca:site:check fails when the committed copy no longer matches.
 */
final class Catalogue
{
    private const TYPES = [
        'text' => 'text', 'textarea' => 'plain text over several lines', 'bard' => 'text editor', 'markdown' => 'markdown text',
        'assets' => 'images or files', 'select' => 'choice', 'button_group' => 'choice', 'radio' => 'choice',
        'checkboxes' => 'choices, any number', 'toggle' => 'on or off', 'replicator' => 'list of items', 'grid' => 'rows',
        'group' => 'group of fields', 'link' => 'link', 'entries' => 'entries', 'terms' => 'taxonomy terms', 'form' => 'form',
        'video' => 'video URL', 'code' => 'code', 'table' => 'table', 'color' => 'colour', 'date' => 'date',
        'integer' => 'whole number', 'float' => 'number', 'list' => 'list of text', 'slug' => 'slug', 'icon' => 'icon',
    ];

    /** Fields the editor shows that hold no content. */
    private const DISPLAY_ONLY = ['section', 'spacer', 'html'];

    public static function relativePath(): string
    {
        return trim((string) config('statamic-tools.site.catalogue_path', 'resources/site/catalogue.md'), '/');
    }

    public static function path(): string
    {
        return base_path(self::relativePath());
    }

    /** The catalogue as this site's fieldsets and guidance files stand now. */
    public static function build(): string
    {
        $blocks = Blocks::pageBuilder();
        $editorBlocks = array_values(array_map(fn (array $b) => $b['display'], array_filter($blocks, fn (array $b) => Blocks::holdsTextEditor($b['fields']))));

        return self::render($blocks, Blocks::article(), $editorBlocks, Blocks::textEditorParents(), Docs::markdown(...), Docs::design());
    }

    /**
     * @param  array<string, array<string, mixed>>  $blocks  page builder blocks, as Blocks::pageBuilder() returns them
     * @param  array<string, array<string, mixed>>  $sets  text editor sets, as Blocks::article() returns them
     * @param  array<int, string>  $editorBlocks  names of the blocks whose content holds the text editor
     * @param  array<int, string>  $editorParents  set types that hold the text editor directly
     * @param  callable(string, string): array<string, mixed>  $docs  guidance for a kind and handle, as Docs::markdown() returns it
     * @param  array<string, mixed>  $design  the site-wide design guidance, as Docs::design() returns it
     */
    public static function render(array $blocks, array $sets, array $editorBlocks, array $editorParents, callable $docs, array $design = []): string
    {
        $docsPath = trim((string) config('statamic-tools.site.docs_path', 'resources/site'), '/');
        $lines = [
            '# Block catalogue',
            '',
            "_Generated by `php please avoca:site:catalogue` from this site's fieldsets and the guidance files in `{$docsPath}`. Do not edit it by hand: change a fieldset or a guidance file, then run the command again._",
            '',
            "Build this site's pages only from the page builder blocks and text editor sets listed here, using exactly these handles. For a choice field, use one of the option keys shown. A field marked \"Only when\" is hidden in the editor unless that holds, so leave it out otherwise. A required field must have a value.",
            '',
        ];
        $lines = [...$lines, ...self::designLines($design), '## Page builder blocks', ''];
        foreach ($blocks as $block) {
            $note = Blocks::holdsTextEditor($block['fields']) ? "This block's content can include the text editor sets listed under Text editor sets." : null;
            $lines = [...$lines, ...self::entry('blocks', $block, $docs, [], $note)];
        }
        $lines[] = '## Text editor sets';
        $lines[] = '';
        $lines[] = $editorBlocks === []
            ? 'These go inside the text editor.'
            : 'These go inside the text editor, which these blocks hold: '.Conditions::list($editorBlocks, 'and').'.';
        $lines[] = '';
        foreach ($sets as $set) {
            $lines = [...$lines, ...self::entry('sets', $set, $docs, $editorParents, null)];
        }

        return rtrim(implode("\n", $lines))."\n";
    }

    /** The written design guidance under one heading, before the blocks. Nothing when none is written. */
    private static function designLines(array $design): array
    {
        $lines = [];
        foreach ($design['sections'] ?? [] as [$heading, $text]) {
            $lines = [...$lines, "### {$heading}", '', $text, ''];
        }
        if (($design['notes_for_ai'] ?? '') !== '') {
            $lines = [...$lines, '### Notes for AI', '', $design['notes_for_ai'], ''];
        }

        return $lines === [] ? [] : ['## Design', '', 'These rules apply to every page, block and set.', '', ...$lines];
    }

    private static function entry(string $kind, array $item, callable $docs, array $parentTypes, ?string $note): array
    {
        $guide = $docs($kind, $item['handle']);
        $lines = ["### {$item['display']} (`{$item['handle']}`)", ''];
        $description = trim((string) (($guide['description'] ?? '') ?: ($item['instructions'] ?? '')));
        $group = trim((string) ($item['group'] ?? ''));
        $place = $group === '' ? '' : "Listed under {$group} in the ".($kind === 'sets' ? 'text editor' : 'page builder').'.';
        foreach (array_filter([$description, $place, (string) $note]) as $paragraph) {
            $lines = [...$lines, $paragraph, ''];
        }
        foreach (['when_to_use' => 'When to use', 'when_not_to_use' => 'When not to use'] as $key => $heading) {
            if (($guide[$key] ?? '') !== '') {
                $lines = [...$lines, "#### {$heading}", '', $guide[$key], ''];
            }
        }
        foreach ($guide['other'] ?? [] as [$heading, $text]) {
            $lines = [...$lines, "#### {$heading}", '', $text, ''];
        }
        if (($guide['notes_for_ai'] ?? '') !== '') {
            $lines = [...$lines, '#### Notes for AI', '', $guide['notes_for_ai'], ''];
        }
        $fields = self::fieldLines($item['fields'], null, $parentTypes, $item['handle'], $kind === 'sets' ? 'set' : 'block', 0);

        return [...$lines, '#### Fields', '', ...($fields === [] ? ['- None.'] : $fields), ''];
    }

    private static function fieldLines(Fields $fields, ?Fields $parent, array $parentTypes, string $ownType, string $noun, int $depth): array
    {
        $lines = [];
        $pad = str_repeat('  ', $depth);
        foreach ($fields->all() as $handle => $field) {
            if (in_array($field->type(), self::DISPLAY_ONLY, true)) {
                continue;
            }
            $when = Conditions::describe($field, $fields, $parent, $parentTypes, $noun);
            if (! $when['visible']) {
                continue; // hidden in the editor wherever this block or set can sit
            }
            $lines[] = $pad.'- '.self::describe((string) $handle, $field, $when['words']);
            if ($field->type() === 'replicator') {
                foreach (self::setsOf($field) as $setHandle => $set) {
                    $lines[] = $pad."  - Each `{$setHandle}` item".(isset($set['display']) ? " ({$set['display']})" : '').' has:';
                    $lines = [...$lines, ...self::fieldLines(new Fields($set['fields'] ?? []), $fields, [$ownType], (string) $setHandle, $noun, $depth + 2)];
                }
            } elseif (in_array($field->type(), ['group', 'grid'], true)) {
                $lines = [...$lines, ...self::fieldLines(new Fields($field->get('fields', [])), $fields, [$ownType], $ownType, $noun, $depth + 1)];
            }
        }

        return $lines;
    }

    private static function describe(string $handle, Field $field, ?string $when): string
    {
        $type = $field->type();
        if ($type === 'revealer') {
            $parts = ["`{$handle}`: {$field->display()}. A switch in the editor that shows the fields depending on it. It saves nothing, so write the fields it reveals directly"];
        } else {
            $parts = ["`{$handle}`: {$field->display()}. ".Str::ucfirst(self::TYPES[$type] ?? $type)." (`{$type}`)".($field->isRequired() ? ', required' : '')];
        }
        if (($limits = self::limits($field)) !== null) {
            $parts[] = $limits;
        }
        $options = in_array($type, ['select', 'button_group', 'radio', 'checkboxes'], true) ? Blocks::options($field) : [];
        if ($options !== []) {
            $parts[] = 'Options: '.implode(', ', array_map(fn ($key, $label) => "`{$key}` {$label}", array_keys($options), $options));
            $default = $field->get('default');
            if (is_scalar($default) && array_key_exists((string) $default, $options)) {
                $parts[] = "Default `{$default}`";
            }
        } elseif ($type === 'toggle') {
            $parts[] = 'Default '.($field->get('default') ? 'on' : 'off');
        }
        if ($type === 'bard' && ! empty($field->get('sets'))) {
            $parts[] = 'Can include the text editor sets listed under Text editor sets';
        }
        if ($when !== null) {
            $parts[] = $when;
        }
        if (($help = trim((string) $field->get('instructions'))) !== '') {
            $parts[] = 'Help: '.rtrim($help, '.');
        }

        return implode('. ', $parts).'.';
    }

    private static function limits(Field $field): ?string
    {
        $bits = [];
        foreach ([['min_files', 'max_files', 'file'], ['min_items', 'max_items', 'item'], ['min_sets', 'max_sets', 'item'], ['min_rows', 'max_rows', 'row']] as [$minKey, $maxKey, $unit]) {
            $min = (int) $field->get($minKey);
            $max = (int) $field->get($maxKey);
            $bits[] = match (true) {
                $max === 1 => "at most one {$unit}",
                $min > 0 && $max > 0 => "{$min} to {$max} {$unit}s",
                $max > 0 => "at most {$max} {$unit}s",
                $min === 1 => "at least one {$unit}",
                $min > 1 => "at least {$min} {$unit}s",
                default => null,
            };
        }
        if (($chars = (int) $field->get('character_limit')) > 0) {
            $bits[] = "at most {$chars} characters";
        }
        $bits = array_values(array_filter($bits));

        return $bits === [] ? null : Str::ucfirst(implode(', ', $bits));
    }

    private static function setsOf(Field $field): array
    {
        $flat = [];
        foreach ($field->get('sets', []) as $groupHandle => $group) {
            $members = isset($group['sets']) && is_array($group['sets']) ? $group['sets'] : [$groupHandle => $group];
            foreach ($members as $handle => $set) {
                $flat[$handle] = $set;
            }
        }

        return $flat;
    }
}
